sudo: required
language: node_js
node_js: 
  - "node"
services:
  - docker

before_install:
  - docker build -t kumawatanupriya/frontend -f Dockerfile.dev .

script:
  - docker run kumawatanupriya/frontend npm run test -- --coverage
